Отправляю лабораторную про перегрузку операторов
v-v-barkov-mtuci/CppLab5 pull request #3
Opened 2022-01-04 14:46 UTC by wakoo1337

2022-01-08 14:55 UTC, v-v-barkov-mtuci requested changes
Надо поправить

2022-01-08 14:55 UTC, v-v-barkov-mtuci commented on MathLib/Math.ixx
> +		double real;
Здесь нужно по варианту смотреть
Либо real и imag, либо mod и arg
Но никак не все 4 поля

2022-01-08 14:55 UTC, v-v-barkov-mtuci commented on MathLib/Math.ixx
> +		void UpdateExp();
После удаления одной из пар, эти два метода будут неактуальны

2022-01-08 14:55 UTC, v-v-barkov-mtuci commented on MathLib/Math.ixx
> +	Complex operator + (const Complex a, const Complex b);
Аргументы здесь тоже лучше по ссылке передавать

2022-01-08 14:55 UTC, v-v-barkov-mtuci commented on MathLib/Math.ixx
> +		static int GCD(int a, int b);
Зачем они нам нужны? У нас же уже есть функции FindGreatestCommonDivisor и FindLeastCommonMultiple
abs вообще стандартная функция

2022-01-08 14:55 UTC, v-v-barkov-mtuci commented on MathLib/RatMath.cpp
> +	return Rational::GCD(a, b);
Нарушен SRP - rational не имеет никакого отношения к вычислению наибольшего общего делителя, наименьшего общего кратного

2022-01-09 16:22 UTC, v-v-barkov-mtuci requested changes
Нужно как можно меньше дублирующего кода

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	mod = (mod < 0.000000000001) ? 0.0 : mod; // �� ���������� ���� TestIfSubIsNotCommutative, �.�. ��� �������� � ��������������� ������������� ������ 0 ���������� ����� �����
Зачем это?

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	mod = (mod < 0.000000000001) ? 0.0 : mod; // �� ���������� ���� TestIfSubIsNotCommutative, �.�. ��� �������� � ��������������� ������������� ������ 0 ���������� ����� �����
Да и списки инициализации неплохо бы использовать

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	mod = hypot(new_real, old_imag);
Повторяющийся код. Нужно в какую-то функцию вынести.

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	const double old_real = Re();
Можно operator-- вызвать на this

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	const double this_imag = Im();
Для конвертации можно использовать FromExponentialForm/FromAlgebraicForm
Можно создать временный объект и сделть std::swap с *this

2022-01-09 16:22 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	const double a_real = a.Re();
Чтобы не дублировать код, можно через += сделать

2022-01-09 16:23 UTC, v-v-barkov-mtuci commented on MathLib/CpxMath.cpp
> +	mod = (mod < 0.000000000001) ? 0.0 : mod; // �� ���������� ���� TestIfSubIsNotCommutative, �.�. ��� �������� � ��������������� ������������� ������ 0 ���������� ����� �����
В UTF-8 нужно сохранить файл

2022-01-09 16:33 UTC, v-v-barkov-mtuci commented
Не увидел Проект Lab5, в котором функции вычисляются

2022-01-09 22:21 UTC, wakoo1337 commented on MathLib/CpxMath.cpp
> +	mod = hypot(new_real, old_imag);
Вынес в DeltaRealPart

2022-01-12 13:21 UTC, v-v-barkov-mtuci submitted a review, later dismissed
Если тесты пройдут, то ок

2022-01-21 11:42 UTC, v-v-barkov-mtuci approved these changes

2022-01-21 11:43 UTC, merged